#  nnUNet_predict -i data_nii_gz/ -o nnunet_output/ -t 525 -m 3d_fullres -f all -chk model_best > nnunet_predict_fold_5_run1.txt & 

#  nnUNet_predict -i data_nii_gz/ -o nnunet_output/ -t 526 -m 3d_fullres -f all -chk model_best > nnunet_predict_fold_6_run1.txt & 

#3d_low_res
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_0/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_0/gtv_test/uncut_scale_unproc/nnunet_output_lowres/ -t 520 -m 3d_lowres -f all -chk model_best > oct6_nnunet_3DLowRes_predict_fold_0_run1.txt 
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_1/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_1/gtv_test/uncut_scale_unproc/nnunet_output_lowres/ -t 521 -m 3d_lowres -f all -chk model_best > oct6_nnunet_3DLowRes_predict_fold_1_run2.txt 
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_2/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_2/gtv_test/uncut_scale_unproc/nnunet_output_lowres/ -t 522 -m 3d_lowres -f all -chk model_best > oct6_nnunet_3DLowRes_predict_fold_2_run3.txt 
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_3/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_3/gtv_test/uncut_scale_unproc/nnunet_output_lowres/ -t 523 -m 3d_lowres -f all -chk model_best > oct6_nnunet_3DLowRes_predict_fold_3_run4.txt  
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_4/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_4/gtv_test/uncut_scale_unproc/nnunet_output_lowres/ -t 524 -m 3d_lowres -f all -chk model_best > oct6_nnunet_3DLowRes_predict_fold_4_run5.txt  
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_5/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_5/gtv_test/uncut_scale_unproc/nnunet_output_lowres/ -t 525 -m 3d_lowres -f all -chk model_best > oct6_nnunet_3DLowRes_predict_fold_5_run6.txt  
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_6/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_6/gtv_test/uncut_scale_unproc/nnunet_output_lowres/ -t 526 -m 3d_lowres -f all -chk model_best > oct6_nnunet_3DLowRes_predict_fold_6_run7.txt  

#2d
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_0/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_0/gtv_test/uncut_scale_unproc/nnunet_output_2d/ -t 520 -m 2d -f all -chk model_best > oct6_nnunet_2D_predict_fold_0_run8.txt 
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_1/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_1/gtv_test/uncut_scale_unproc/nnunet_output_2d/ -t 521 -m 2d -f all -chk model_best > oct6_nnunet_2D_predict_fold_1_run9.txt  
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_2/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_2/gtv_test/uncut_scale_unproc/nnunet_output_2d/ -t 522 -m 2d -f all -chk model_best > oct6_nnunet_2D_predict_fold_2_run10.txt  
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_3/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_3/gtv_test/uncut_scale_unproc/nnunet_output_2d/ -t 523 -m 2d -f all -chk model_best > oct6_nnunet_2D_predict_fold_3_run11.txt  
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_4/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_4/gtv_test/uncut_scale_unproc/nnunet_output_2d/ -t 524 -m 2d -f all -chk model_best > oct6_nnunet_2D_predict_fold_4_run12.txt  
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_5/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_5/gtv_test/uncut_scale_unproc/nnunet_output_2d/ -t 525 -m 2d -f all -chk model_best > oct6_nnunet_2D_predict_fold_5_run13.txt  
nnUNet_predict -i /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_6/gtv_test/uncut_scale_unproc/data_nii_gz/ -o /media/disk1/jansen/code_rad/Dataset_Rad3/iteration_6/gtv_test/uncut_scale_unproc/nnunet_output_2d/ -t 526 -m 2d -f all -chk model_best > oct6_nnunet_2D_predict_fold_6_run14.txt  